# Generated by Django 4.2 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rice",
            old_name="brand_name",
            new_name="brand",
        ),
        migrations.RemoveField(
            model_name="rice",
            name="picture",
        ),
        migrations.AddField(
            model_name="rice",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="rice_images/"),
        ),
    ]
