# Generated by Django 4.2 on 2024-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_rename_brand_name_rice_brand_remove_rice_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rice",
            name="brand",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
