# Generated by Django 4.2 on 2024-08-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_rice_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("session_key", models.CharField(max_length=40)),
                (
                    "rice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.rice"
                    ),
                ),
            ],
        ),
    ]
