# Generated by Django 4.2 on 2024-08-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_order_status_alter_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
